In [1]:
import tensorflow as tf

# lecture 2

In [2]:
vec, mat = tf.constant([2,2], name="vector"), tf.constant([[0,1],[3,4]], name="matrix")

In [3]:
tf.zeros(vec, tf.int32)

<tf.Tensor 'zeros:0' shape=(2, 2) dtype=int32>

In [7]:
with tf.Session() as s:
    print(tf.zeros(vec, tf.int32).eval())
    print(vec, vec.eval())
    print(mat, mat.eval())

[[0 0]
 [0 0]]
Tensor("vector:0", shape=(2,), dtype=int32) [2 2]
Tensor("matrix:0", shape=(2, 2), dtype=int32) [[0 1]
 [3 4]]


In [9]:
with tf.Session() as s:
    print(tf.zeros_like(vec), tf.zeros_like(vec).eval())

Tensor("zeros_like:0", shape=(2,), dtype=int32) [0 0]


In [10]:
tf.InteractiveSession()

In [12]:
tf.ones([5,2]), tf.ones([5,2]).eval()

(<tf.Tensor 'ones_1:0' shape=(5, 2) dtype=float32>, array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32))

In [13]:
tf.fill([2,5],7).eval(), tf.fill([2,5],7)

(array([[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]]), <tf.Tensor 'Fill_1:0' shape=(2, 5) dtype=int32>)

In [14]:
tf.lin_space(1,9,0.8).eval()

TypeError: Value passed to parameter 'start' has DataType int32 not in list of allowed values: bfloat16, float32, float64

In [15]:
tf.lin_space(1.0,9.0,0.8).eval()

TypeError: Value passed to parameter 'num' has DataType float32 not in list of allowed values: int32, int64

In [19]:
print(tf.lin_space(1.0,9.0,8).eval())
len(tf.lin_space(1.0,9.0,8).eval())

[1.        2.142857  3.2857144 4.4285717 5.571429  6.714286  7.8571434
 9.       ]


8

In [24]:
print(tf.range(0., 11, 2).eval())
print(tf.range(0., 12., 2).eval())

[ 0.  2.  4.  6.  8. 10.]
[ 0.  2.  4.  6.  8. 10.]


array([ 0.,  2.,  4.,  6.,  8., 10.], dtype=float32)

In [27]:
for m in range(9,3,-1):
    print(tf.range(0., 12 + 10**(-m), 2).eval(), 12+10**(-m))

[ 0.  2.  4.  6.  8. 10.] 12.000000001
[ 0.  2.  4.  6.  8. 10.] 12.00000001
[ 0.  2.  4.  6.  8. 10.] 12.0000001
[ 0.  2.  4.  6.  8. 10. 12.] 12.000001
[ 0.  2.  4.  6.  8. 10. 12.] 12.00001
[ 0.  2.  4.  6.  8. 10. 12.] 12.0001


In [35]:
print(mat.eval())
tf.random_shuffle(mat).eval()

[[0 1]
 [3 4]]


array([[3, 4],
       [0, 1]])

In [106]:
mat = tf.random_normal([3,2,2])
mat = tf.constant(mat.eval())
print(mat.eval())

[[[ 0.8095361   0.7171352 ]
  [-0.3160582   0.57229537]]

 [[ 2.4878109  -1.2849234 ]
  [-0.17564026 -0.17201276]]

 [[ 2.4339795  -0.20659003]
  [ 1.1018362  -1.1203471 ]]]


In [107]:
# tf.random_shuffle은 첫 번째 디멘션으로만 섞는다.
import numpy as np
#mat = tf.constant([[[5,2],[2,1]],[[1,1],[3,2]]])
print(mat.eval())
temp = [tf.random_shuffle(mat).eval()]
for _ in range(50):
    sfd = tf.random_shuffle(mat).eval()
    if not (sum(1 for e in temp if np.all(sfd==e))):
        temp.append(sfd)
len(temp), temp

[[[ 0.8095361   0.7171352 ]
  [-0.3160582   0.57229537]]

 [[ 2.4878109  -1.2849234 ]
  [-0.17564026 -0.17201276]]

 [[ 2.4339795  -0.20659003]
  [ 1.1018362  -1.1203471 ]]]


(6, [array([[[ 2.4339795 , -0.20659003],
          [ 1.1018362 , -1.1203471 ]],
  
         [[ 2.4878109 , -1.2849234 ],
          [-0.17564026, -0.17201276]],
  
         [[ 0.8095361 ,  0.7171352 ],
          [-0.3160582 ,  0.57229537]]], dtype=float32),
  array([[[ 2.4339795 , -0.20659003],
          [ 1.1018362 , -1.1203471 ]],
  
         [[ 0.8095361 ,  0.7171352 ],
          [-0.3160582 ,  0.57229537]],
  
         [[ 2.4878109 , -1.2849234 ],
          [-0.17564026, -0.17201276]]], dtype=float32),
  array([[[ 0.8095361 ,  0.7171352 ],
          [-0.3160582 ,  0.57229537]],
  
         [[ 2.4878109 , -1.2849234 ],
          [-0.17564026, -0.17201276]],
  
         [[ 2.4339795 , -0.20659003],
          [ 1.1018362 , -1.1203471 ]]], dtype=float32),
  array([[[ 2.4878109 , -1.2849234 ],
          [-0.17564026, -0.17201276]],
  
         [[ 0.8095361 ,  0.7171352 ],
          [-0.3160582 ,  0.57229537]],
  
         [[ 2.4339795 , -0.20659003],
          [ 1.1018362 , -1.1203471 ]]

In [115]:
# truncated는 2 std 밖의 값은 뽑지 않는다.
max_truncated, max_normal = -9, -9
for _ in range(100):
    max_truncated = max(np.max(tf.truncated_normal([1,10]).eval()), max_truncated)
    max_normal = max(np.max(tf.random_normal([1,10]).eval()), max_normal)
max_truncated, max_normal

(1.9893097, 3.4579384)

In [131]:
print(mat.eval(),[3,2,2])
print(tf.random_crop(mat,tf.constant([2,1,2])).eval(),'2,1,2')
print(tf.random_crop(mat,tf.constant([3,1,1])).eval(),'3,1,1')
print(tf.random_crop(mat,tf.constant([2,2,1])).eval(),'2,2,1')

[[[ 0.8095361   0.7171352 ]
  [-0.3160582   0.57229537]]

 [[ 2.4878109  -1.2849234 ]
  [-0.17564026 -0.17201276]]

 [[ 2.4339795  -0.20659003]
  [ 1.1018362  -1.1203471 ]]] [3, 2, 2]
[[[-0.17564026 -0.17201276]]

 [[ 1.1018362  -1.1203471 ]]] 2,1,2
[[[0.8095361]]

 [[2.4878109]]

 [[2.4339795]]] 3,1,1
[[[ 0.8095361 ]
  [-0.3160582 ]]

 [[ 2.4878109 ]
  [-0.17564026]]] 2,2,1


In [144]:
with tf.Session() as s:
    print(s.run(tf.report_uninitialized_variables()))

[]


In [150]:
tf.get_variable?

In [156]:
W = tf.Variable(10)
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())
    W.assign(100).eval()
    print(W.eval())
    sess.run(W.assign(1001))
    print(W.eval())

10
100
1001


In [159]:
W = tf.Variable(123)
W.assign(100).eval()
W.eval()

100

In [160]:
tf.Variable.initialized_value?

# lecture 3

In [1]:

import tensorflow as tf


import utils


DATA_FILE = "data/birth_life_2010.txt"


# Step 1: read in data from the .txt file

# data is a numpy array of shape (190, 2), each row is a datapoint

data, n_samples = utils.read_birth_life_data(DATA_FILE)


# Step 2: create placeholders for X (birth rate) and Y (life expectancy)

X = tf.placeholder(tf.float32, name='X')

Y = tf.placeholder(tf.float32, name='Y')


# Step 3: create weight and bias, initialized to 0

w = tf.get_variable('weights', initializer=tf.constant(0.0))

b = tf.get_variable('bias', initializer=tf.constant(0.0))


# Step 4: construct model to predict Y (life expectancy from birth rate)
Y_predicted = w * X + b 


# Step 5: use the square error as the loss function

loss = tf.square(Y - Y_predicted, name='loss')


# Step 6: using gradient descent with learning rate of 0.01 to minimize loss

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001).minimize(loss)

 

with tf.Session() as sess:

    # Step 7: initialize the necessary variables, in this case, w and b

    sess.run(tf.global_variables_initializer()) 

    

    # Step 8: train the model

    for i in range(100): # run 100 epochs

        for x, y in data:

            # Session runs train_op to minimize loss

            sess.run(optimizer, feed_dict={X: x, Y:y}) 

    

    # Step 9: output the values of w and b
    w_out, b_out = sess.run([w, b]) 
    print('loss', loss, w_out, b_out)

loss Tensor("loss:0", dtype=float32) -6.0702143 84.92951


In [1]:
def huber_loss(labels,predictions, delta=14.0):
    residual = tf.abs(labels - predictions)
    def f1(): return 0.5 * tf.square(residual)
    def f2(): return delta * residual - 0.5 * tf.square(delta)
    return tf.cond(residual < delta, f1, f2)

In [2]:

import tensorflow as tf


import utils


DATA_FILE = "data/birth_life_2010.txt"


# Step 1: read in data from the .txt file

# data is a numpy array of shape (190, 2), each row is a datapoint

data, n_samples = utils.read_birth_life_data(DATA_FILE)


# Step 2: create placeholders for X (birth rate) and Y (life expectancy)

X = tf.placeholder(tf.float32, name='X')

Y = tf.placeholder(tf.float32, name='Y')


# Step 3: create weight and bias, initialized to 0

w = tf.get_variable('weights', initializer=tf.constant(0.0))

b = tf.get_variable('bias', initializer=tf.constant(0.0))


# Step 4: construct model to predict Y (life expectancy from birth rate)
Y_predicted = w * X + b 


# Step 5: use the square error as the loss function

#loss = tf.square(Y - Y_predicted, name='loss')
loss = huber_loss(Y, Y_predicted)


# Step 6: using gradient descent with learning rate of 0.01 to minimize loss

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001).minimize(loss)

 

with tf.Session() as sess:

    # Step 7: initialize the necessary variables, in this case, w and b

    sess.run(tf.global_variables_initializer()) 

    

    # Step 8: train the model

    for i in range(100): # run 100 epochs

        for x, y in data:

            # Session runs train_op to minimize loss

            sess.run(optimizer, feed_dict={X: x, Y:y}) 

    

    # Step 9: output the values of w and b
    w_out, b_out = sess.run([w, b]) 
    print('loss', loss, w_out, b_out)

loss Tensor("cond/Merge:0", dtype=float32) -4.2249994 78.485054


In [4]:
data, n_samples = utils.read_birth_life_data('data/birth_life_2010.txt')

#dataset 이용
dataset = tf.data.Dataset.from_tensor_slices((data[:,0], data[:,1]))
print(dataset.output_types, dataset.output_shapes)
#...

(tf.float32, tf.float32) (TensorShape([]), TensorShape([]))


In [6]:
iterator = dataset.make_one_shot_iterator()
X, Y = iterator.get_next()
with tf.Session() as sess:
    for i in range(5):
        print(sess.run([X, Y]))

[1.822, 74.82825]
[3.869, 70.81949]
[3.911, 72.15066]
[5.578, 61.999855]
[1.579, 73.92766]


In [ ]:
# gradient 직접 수정하기
'''
optimizer.compute_gradients(loss, list of variables)
-> [(gradient, variable), ... ]  반환. 여기에 수정 가한 뒤
optimizer.apply_gradients(적용할 변수)

'''

# gradient 멈추기
'''
tf.stop_gradient 사용.
'''

# 특정 gradient만 계산하기
'''
tf.gradients 사용
'''

In [ ]:
mnist_folder = 'data/mnist'
utils.download_mnist(mnist_folder)
train, val, test = utils.read_mnist(mnist_folder, flatten = True)

train_data = tf.data.Dataset.from_tensor_slices(train)
test_data = tf.data.Dataset.from_tensor_slices(test)

batch_size = 64

train_data = train_data.batch(batch_size)
test_data = test_data.batch(batch_size)

iterator = tf.data.Iterator.from_structure(train_data.output_types, train_data.output_shapes)

img, label = iterator.get_next()

train_init = iterator.make_initializer(train_data)
test_init = iterator.make_initializer(test_data)

with tf.Session() as sess:
    #tf.nn.conv2d()

# lecture 4

In [1]:
import tensorflow as tf
tf.enable_eager_execution()

print("TensorFlow version: {}".format(tf.VERSION))
print("Eager execution: {}".format(tf.executing_eagerly()))

TensorFlow version: 1.11.0
Eager execution: True


In [2]:
x = [[2.]]
m = tf.matmul(x, x)
print(m)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [5]:
import numpy as np 

x = tf.constant([1., 2., 3.])
assert type(x.numpy()) == np.ndarray
squared = np.square(x)

squared = tf.square(squared)

for i in x:
    print(i)
    
print(x.shape)
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        print(x[i,j])

tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(3.0, shape=(), dtype=float32)
(3,)


IndexError: list index out of range

In [7]:
def square(x):
    return x ** 2

import tensorflow.contrib.eager as tfe
grad = tfe.gradients_function(square)

print(square(3.))
print(grad(3.))

9.0
[<tf.Tensor: id=61, shape=(), dtype=float32, numpy=6.0>]


In [8]:
x = tf.Variable(2.)
def loss(y):
    return (y - x ** 2) ** 2

grad = tfe.implicit_gradients(loss)

print(loss(7.))
print(grad(7.))

tf.Tensor(9.0, shape=(), dtype=float32)
[(<tf.Tensor: id=119, shape=(), dtype=float32, numpy=-24.0>, <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>)]


In [18]:
i = tf.Variable([[1.],[2.]])
w1 = tf.Variable([1.,1.])
w2 = tf.multiply(w1,i)
grad = tfe.implicit_gradients(w2)
grad(1.)

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object is not callable